"""Seed initial patients and users if the database is empty."""
import logging
import uuid
from .database import SessionLocal
from .models import Patient, User

logger = logging.getLogger(__name__)

PATIENTS = [
    {"id": 1, "prescriber": "Chorny, Volodymyr", "referral_date": "2022-06-13", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 24, "last_comment": "3/4 - Patient recently received a bridge shipment. NCM assistance needed to ask the patient to follow up with their HCP.", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Health Exchange", "primary_payer": "Florida Health Care Plans", "primary_pbm": "OptumRx", "secondary_channel": "Medicaid", "territory": "Orlando FL", "region": "Southeast", "language": "Spanish", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2022-08-08", "last_ship_date": "2026-02-23"},
    {"id": 2, "prescriber": "Hernandez, Dunia", "referral_date": "2026-01-16", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 20, "last_comment": "3/4 - Tatiana with HCP responded and advised that the 1LA was submitted to plan on 2/27.", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Commercial", "primary_payer": "CVS Health (Aetna)", "primary_pbm": "CVS Caremark RX", "secondary_channel": None, "territory": "Miami FL", "region": "Southeast", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-01-21", "last_ship_date": "2026-03-02"},
    {"id": 3, "prescriber": "Wang, Gregory", "referral_date": "2024-04-03", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 15, "last_comment": "Appeal needs to be submitted by HCP", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Medicare", "primary_payer": "UnitedHealth Group, Inc.", "primary_pbm": "OptumRx", "secondary_channel": None, "territory": "DC/Virginia", "region": "Northeast", "language": "English", "hippa_consent": "Electronic", "program_type": "BRIDGE", "first_ship_date": "2024-05-20", "last_ship_date": "2026-03-05"},
    {"id": 4, "prescriber": "Hsu, Alice", "referral_date": "2026-02-02", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 14, "last_comment": None, "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Commercial", "primary_payer": "Express Scripts PBM", "primary_pbm": "Express Scripts PBM", "secondary_channel": None, "territory": "Dallas TX", "region": "Central", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-02-20", "last_ship_date": "2026-03-04"},
    {"id": 5, "prescriber": "Duffy, Margaret", "referral_date": "2026-02-06", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 14, "last_comment": "Appeal needs to be submitted by HCP", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Commercial", "primary_payer": "CVS Health (Aetna)", "primary_pbm": "CVS Caremark RX", "secondary_channel": None, "territory": "Western PA/Upstate NY", "region": "Northeast", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-02-18", "last_ship_date": "2026-02-26"},
    {"id": 6, "prescriber": "Gillespie, Heather", "referral_date": "2023-03-03", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 11, "last_comment": "Appeal needs to be submitted by HCP", "latest_hub_sub_status": "Bridge 30+ Days Dispensed", "primary_channel": "Commercial", "primary_payer": "Dept. of Defense - TRICARE", "primary_pbm": "Express Scripts PBM", "secondary_channel": None, "territory": "Los Angeles East", "region": "West", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2023-07-26", "last_ship_date": "2026-02-20"},
    {"id": 7, "prescriber": "Garcia Sanchez, Hermes", "referral_date": "2025-12-15", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 10, "last_comment": "Appeal needs to be resubmitted by HCP", "latest_hub_sub_status": "No MD Response for Missing Information", "primary_channel": "Health Exchange", "primary_payer": "Oscar Insurance", "primary_pbm": "CVS Caremark RX", "secondary_channel": None, "territory": "North Georgia", "region": "Southeast", "language": "Spanish", "hippa_consent": "Written", "program_type": None, "first_ship_date": None, "last_ship_date": None},
    {"id": 8, "prescriber": "Maya Villamizar, Juan Jose", "referral_date": "2025-10-10", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 8, "last_comment": "2/23 - SPOC - Hector replied to the email and sent in clinicals.", "latest_hub_sub_status": "Prescriber Decision", "primary_channel": "Managed Medicaid", "primary_payer": "State of Florida", "primary_pbm": "Humana PBM", "secondary_channel": "Medicaid", "territory": "Fort Lauderdale FL", "region": "Southeast", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2025-10-23", "last_ship_date": "2025-10-23"},
    {"id": 9, "prescriber": "Vasquez, Karina", "referral_date": "2025-12-22", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 7, "last_comment": "Verify intent to appeal &/or obtain PA denial letter/appeal documentation", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Commercial", "primary_payer": "CareFirst, Inc.", "primary_pbm": "CVS Caremark RX", "secondary_channel": None, "territory": "South Texas TX", "region": "Central", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-01-07", "last_ship_date": "2026-03-05"},
    {"id": 10, "prescriber": "Caroway, Megan", "referral_date": "2023-03-28", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 2, "last_comment": "Verify intent to appeal &/or obtain PA denial letter/appeal documentation", "latest_hub_sub_status": "New Script Received", "primary_channel": "Commercial", "primary_payer": "CVS Health (Aetna)", "primary_pbm": "CVS Caremark RX", "secondary_channel": "Commercial (Third Party)", "territory": "Kentuckiana", "region": "Northeast", "language": "English", "hippa_consent": "Written", "program_type": "COMM", "first_ship_date": "2023-06-01", "last_ship_date": "2024-08-02"},
    {"id": 11, "prescriber": "ALDERSON, THOMAS", "referral_date": "2026-01-27", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Appeal letter sent to HCP", "aging_of_status": 1, "last_comment": "2/11 - Sent the below to ISS: The old CMM key expired and we had to create a new one.", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Commercial", "primary_payer": "Blue Cross and Blue Shield of Kansas", "primary_pbm": "Prime Therapeutics", "secondary_channel": None, "territory": "WS Virtual", "region": "WS Virtual", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-02-19", "last_ship_date": "2026-03-02"},
    {"id": 12, "prescriber": "Nami, Alireza", "referral_date": "2023-04-18", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Clinicals needed", "aging_of_status": 22, "last_comment": "3/4- Any update on this case? BH", "latest_hub_sub_status": "Triage to SP", "primary_channel": "Medicare", "primary_payer": "UnitedHealth Group, Inc.", "primary_pbm": "OptumRx", "secondary_channel": None, "territory": "Charlotte NC", "region": "Southeast", "language": "English", "hippa_consent": "Electronic", "program_type": "BRIDGE", "first_ship_date": "2023-04-28", "last_ship_date": "2026-02-19"},
    {"id": 13, "prescriber": "Sun, Wei", "referral_date": "2026-01-21", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Clinicals needed", "aging_of_status": 9, "last_comment": "Clinicals needed for PA", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Medicare", "primary_payer": "Healthfirst", "primary_pbm": "CVS Caremark RX", "secondary_channel": None, "territory": "Manhattan/Brooklyn NY", "region": "Northeast", "language": "Mandarin Chinese", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-02-24", "last_ship_date": "2026-02-24"},
    {"id": 14, "prescriber": "Maya-Villamizar, Juan", "referral_date": "2023-05-11", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Clinicals needed", "aging_of_status": 4, "last_comment": "2/17: any update on the PA submission?", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Managed Medicaid", "primary_payer": "State of Florida", "primary_pbm": "Humana PBM", "secondary_channel": "Medicaid", "territory": "Fort Lauderdale FL", "region": "Southeast", "language": "Spanish", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2023-05-12", "last_ship_date": "2026-03-03"},
    {"id": 15, "prescriber": "Lagatta, Mark", "referral_date": "2025-12-05", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Clinicals needed", "aging_of_status": 2, "last_comment": "Verify intent to appeal &/or obtain PA denial letter/appeal documentation", "latest_hub_sub_status": "Closed - No HCP response", "primary_channel": "Commercial", "primary_payer": "CVS Health (Aetna)", "primary_pbm": "CVS Caremark RX", "secondary_channel": None, "territory": "Orlando FL", "region": "Southeast", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2025-12-22", "last_ship_date": "2026-01-22"},
    {"id": 16, "prescriber": "Bilal, Mehwish", "referral_date": "2025-09-23", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – HCP drafting appeal letter", "aging_of_status": 30, "last_comment": "Appeal needs to be submitted by HCP", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Commercial", "primary_payer": "Express Scripts PBM", "primary_pbm": "Express Scripts PBM", "secondary_channel": None, "territory": "Nashville TN", "region": "Central", "language": "English", "hippa_consent": "Electronic", "program_type": "BRIDGE", "first_ship_date": "2026-02-26", "last_ship_date": "2026-03-05"},
    {"id": 17, "prescriber": "Bade, Naveen", "referral_date": "2026-01-22", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – HCP drafting appeal letter", "aging_of_status": 29, "last_comment": "Appeal needs to be submitted by HCP", "latest_hub_sub_status": "Triage to SP", "primary_channel": "State Medicaid", "primary_payer": "State of Alabama", "primary_pbm": "DXC Technology", "secondary_channel": None, "territory": "Alabama", "region": "Central", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-02-03", "last_ship_date": "2026-02-16"},
    {"id": 18, "prescriber": "Alvarez, Naiara", "referral_date": "2026-01-23", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – HCP drafting appeal letter", "aging_of_status": 21, "last_comment": "Assist with contacting patient", "latest_hub_sub_status": "HCP Follow-up in Process", "primary_channel": "Commercial", "primary_payer": "Express Scripts PBM", "primary_pbm": "Express Scripts PBM", "secondary_channel": None, "territory": "South Texas TX", "region": "Central", "language": "English", "hippa_consent": "Written", "program_type": None, "first_ship_date": None, "last_ship_date": None},
    {"id": 19, "prescriber": "Patel, Ravi", "referral_date": "2026-02-10", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "On hold – HCP request", "aging_of_status": 18, "last_comment": "Patient on hold pending HCP response", "latest_hub_sub_status": "Trying to Reach Patient", "primary_channel": "Commercial", "primary_payer": "Anthem, Inc.", "primary_pbm": "IngenioRx", "secondary_channel": None, "territory": "Chicago IL", "region": "Central", "language": "English", "hippa_consent": "Written", "program_type": "COMM", "first_ship_date": "2026-02-15", "last_ship_date": "2026-02-28"},
    {"id": 20, "prescriber": "Johnson, Maria", "referral_date": "2025-11-01", "latest_sp_partner": "Orsini Specialty Pharmacy", "latest_sp_status": "Pending", "latest_sp_substatus": "Reopen – Patient restarting therapy", "aging_of_status": 12, "last_comment": "Patient wants to restart – pending PA", "latest_hub_sub_status": "No MD Response for Missing Information", "primary_channel": "Medicare", "primary_payer": "Humana Inc.", "primary_pbm": "Humana PBM", "secondary_channel": None, "territory": "Phoenix AZ", "region": "West", "language": "English", "hippa_consent": "Electronic", "program_type": "COMM", "first_ship_date": "2025-11-15", "last_ship_date": "2025-12-20"},
    {"id": 21, "prescriber": "Kim, David", "referral_date": "2026-01-05", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "PA – Submission in progress", "aging_of_status": 35, "last_comment": "PA submitted – awaiting decision", "latest_hub_sub_status": "Trying to Reach Patient", "primary_channel": "Commercial", "primary_payer": "Cigna Corporation", "primary_pbm": "Express Scripts PBM", "secondary_channel": None, "territory": "San Francisco CA", "region": "West", "language": "Korean", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2026-01-20", "last_ship_date": "2026-02-28"},
    {"id": 22, "prescriber": "Williams, Sandra", "referral_date": "2025-08-14", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "Free goods – Dispensed", "aging_of_status": 5, "last_comment": "Free goods approved and dispensed", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Uninsured", "primary_payer": "Uninsured", "primary_pbm": None, "secondary_channel": None, "territory": "Boston MA", "region": "Northeast", "language": "English", "hippa_consent": "Written", "program_type": "BRIDGE", "first_ship_date": "2025-08-20", "last_ship_date": "2026-03-01"},
    {"id": 196, "prescriber": "Myers, Brenda", "referral_date": "2025-01-28", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "On hold – HCP request", "aging_of_status": 7, "last_comment": "Patient confirmed receipt of shipment", "latest_hub_sub_status": "Trying to Reach Patient", "primary_channel": "Commercial", "primary_payer": "State of Alabama", "primary_pbm": "Humana PBM", "secondary_channel": None, "territory": "Western PA/Upstate NY", "region": "Northeast", "language": "French", "hippa_consent": None, "program_type": "BRIDGE", "first_ship_date": "2023-12-12", "last_ship_date": "2025-01-13"},
    {"id": 197, "prescriber": "Brooks, Jennifer", "referral_date": "2022-02-13", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Clinicals needed", "aging_of_status": 30, "last_comment": "SP confirmed shipment – bridge active", "latest_hub_sub_status": "Closed - No HCP response", "primary_channel": "Health Exchange", "primary_payer": "Centene Corporation", "primary_pbm": "Express Scripts PBM", "secondary_channel": "Medicaid", "territory": "Dallas TX", "region": "Central", "language": "Mandarin Chinese", "hippa_consent": None, "program_type": "BRIDGE", "first_ship_date": "2023-09-12", "last_ship_date": "2024-10-17"},
    {"id": 198, "prescriber": "Brown, Melissa", "referral_date": "2022-07-20", "latest_sp_partner": "Biologics", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Awaiting decision", "aging_of_status": 24, "last_comment": "Free goods approved and dispensed", "latest_hub_sub_status": "Trying to Reach Patient", "primary_channel": "Commercial", "primary_payer": "Dept. of Defense - TRICARE", "primary_pbm": "MedImpact", "secondary_channel": "Medicare", "territory": "Manhattan/Brooklyn NY", "region": "Northeast", "language": "Korean", "hippa_consent": None, "program_type": "COMM", "first_ship_date": "2025-09-18", "last_ship_date": "2026-05-16"},
    {"id": 199, "prescriber": "Adams, Robert", "referral_date": "2024-03-17", "latest_sp_partner": "Orsini Specialty Pharmacy", "latest_sp_status": "Pending", "latest_sp_substatus": "1st level appeal – Awaiting decision", "aging_of_status": 32, "last_comment": "Clinicals needed for PA submission", "latest_hub_sub_status": "Product Shipped - Bridge", "primary_channel": "Health Exchange", "primary_payer": "State of Florida", "primary_pbm": "Capital Rx PBM", "secondary_channel": "Commercial (Third Party)", "territory": "Wisconsin", "region": "Central", "language": "English", "hippa_consent": "Electronic", "program_type": None, "first_ship_date": None, "last_ship_date": None},
    {"id": 200, "prescriber": "Evans, Daniel", "referral_date": "2025-08-28", "latest_sp_partner": "PANTHERx Rare", "latest_sp_status": "Pending", "latest_sp_substatus": "Reopen – Patient restarting therapy", "aging_of_status": 4, "last_comment": "Requested denial letter from plan", "latest_hub_sub_status": "No MD Response for Missing Information", "primary_channel": "Medicaid", "primary_payer": "Dept. of Defense - TRICARE", "primary_pbm": "Prime Therapeutics", "secondary_channel": "Medicaid", "territory": "St. Louis MO", "region": "Central", "language": "English", "hippa_consent": "Written", "program_type": "COMM", "first_ship_date": "2025-04-18", "last_ship_date": "2026-08-17"},
]

SUPERADMINS = [
    {"username": "nick.milero",   "password": "pass123", "name": "Nick Milero",   "team": "Home Office", "role": "admin"},
    {"username": "rick.boulanger","password": "123",     "name": "Rick Boulanger","team": "Home Office", "role": "admin"},
]

USERS = [
    {"id": "ho1", "username": "sarah.johnson", "password": "pass123", "name": "Sarah Johnson", "team": "Home Office", "role": "manager"},
    {"id": "ho2", "username": "mike.chen", "password": "pass123", "name": "Mike Chen", "team": "Home Office", "role": "manager"},
    {"id": "ncm1", "username": "lisa.torres", "password": "pass123", "name": "Lisa Torres", "team": "NCM", "role": "partner"},
    {"id": "ncm2", "username": "james.wright", "password": "pass123", "name": "James Wright", "team": "NCM", "role": "partner"},
    {"id": "sp1", "username": "amy.patel", "password": "pass123", "name": "Amy Patel", "team": "SP", "role": "partner"},
    {"id": "sp2", "username": "robert.kim", "password": "pass123", "name": "Robert Kim", "team": "SP", "role": "partner"},
    {"id": "iss1", "username": "diana.reyes", "password": "pass123", "name": "Diana Reyes", "team": "Sales", "role": "partner"},
    {"id": "iss2", "username": "carlos.vega", "password": "pass123", "name": "Carlos Vega", "team": "Sales", "role": "partner"},
]


def run():
    db = SessionLocal()
    try:
        if db.query(User).count() == 0:
            db.bulk_insert_mappings(User, USERS)
            db.bulk_insert_mappings(Patient, PATIENTS)
            db.commit()
            logger.info("Database seeded with %d users and %d patients", len(USERS), len(PATIENTS))
        else:
            # Migrate: rename ISS → Sales for existing deployments
            iss_users = db.query(User).filter(User.team == "ISS").all()
            if iss_users:
                for u in iss_users:
                    u.team = "Sales"
                db.commit()
                logger.info("Migrated %d ISS users → Sales", len(iss_users))

            # Ensure superadmin accounts exist
            superadmin_usernames = [s["username"] for s in SUPERADMINS]
            for sa in SUPERADMINS:
                if not db.query(User).filter(User.username == sa["username"]).first():
                    db.add(User(id=str(uuid.uuid4()), **sa))
                    logger.info("Created superadmin user: %s", sa["username"])

            # Downgrade any legacy admin → manager (except superadmins)
            legacy = db.query(User).filter(
                User.role == "admin",
                ~User.username.in_(superadmin_usernames)
            ).all()
            for u in legacy:
                u.role = "manager"
                logger.info("Downgraded %s: admin → manager", u.username)

            if legacy or any(not db.query(User).filter(User.username == s["username"]).first() for s in SUPERADMINS):
                db.commit()
    finally:
        db.close()
